//#include "task1_e1.h"
//#include "task2_e1.h"
//#include "task1_e2.h"
//#include "task2_e2.h"
//#include "task1_e3.h"

#include <iostream>
#include <cstddef>
#include <string>
#include <vector>


int main() try {

}
catch(const std::exception& e) {
    std::cerr << "an unexpected error occurred with message"
              << e.what() << "\n";
    return -1;
}
